# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WE_Framework
version:      0.095
version_from: 
installdirs:  site
requires:
    Class::Accessor:               0
    Data::Dumper:                  2.121
    DB_File:                       0
    DB_File::Lock:                 0
    File::Spec:                    0.8
    mixin:                         0
    MLDBM:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
