    {
      url_urlenc => '$%(URL)',
      excerpt_urlenc => '$%(EXCERPT)',
      anchor_urlenc => '$%(ANCHOR)',
      metadescription_urlenc => '$%(METADESCRIPTION)',
      score => '$(SCORE)',
      current => '$(CURRENT)',
      title_urlenc => '$%(TITLE)',
      starsright_urlenc => '$%(STARTRIGHT)',
      starsleft_urlenc => '$%(STARTLEFT)',
      size => '$(SIZE)',
      sizek => '$(SIZEK)',
      percent => '$(PERCENT)',
      modified => '$(MODIFIED)',
      hopcount => '$(HOPCOUNT)',
      docid => '$(DOCID)',
      backlinks => '$(BACKLINKS)',
      description_urlenc => '$%(DESCRIPTION)',
      descriptions_urlenc => '$%(DESCRIPTIONs)',
    },
